'use client'
import { useEffect, useState } from 'react'

type Opportunity = { id: string; title: string; source_url?: string; demand_summary?: string; estimated_margin?: number; confidence?: number; proposed_product?: { name?: string }; proposed_supplier?: { business_name?: string; website_url?: string } }
export default function AdminReview() {
  const [signedIn, setSignedIn] = useState(false); const [items, setItems] = useState<Opportunity[]>([]); const [message, setMessage] = useState(''); const [demandSignal, setDemandSignal] = useState('')
  async function load() { const response = await fetch('/api/admin/review'); if (response.ok) { const data = await response.json(); setItems(data.opportunities); setSignedIn(true) } }
  useEffect(() => { load() }, [])
  async function approve(opportunityId: string) { setMessage('Approving and publishing…'); const response = await fetch('/api/admin/review', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ opportunityId }) }); setMessage(response.ok ? 'Approved. The item is ready for the publishing workflow.' : 'Approval failed.'); if (response.ok) await load() }
  async function queueDiscovery() { const response = await fetch('/api/admin/discovery', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ demandSignal }) }); setMessage(response.ok ? 'Research task queued. The worker will prepare it for review.' : 'Could not queue this research task.'); if (response.ok) setDemandSignal('') }
  if (!signedIn) return <section className="container-section py-16 max-w-md"><h1 className="section-title">Owner sign-in</h1><div className="card mt-6 grid gap-4 p-6"><p className="text-gray-600">The ConnectNetwork dashboard is only available to the authorised owner account.</p><a href="/api/auth/google" className="btn btn-primary">Continue with Google</a>{message && <p role="status" className="text-sm">{message}</p>}</div></section>
  return <section className="container-section py-16"><p className="text-secondary font-semibold">Human approval checkpoint</p><h1 className="section-title mt-2">AI opportunity review</h1><p className="section-subtitle mt-3">AI researches candidates; one approval authorises the supplier and publishes the prepared product.</p><div className="card mt-6 p-5"><label className="grid gap-2 font-medium">What demand should AI research?<textarea value={demandSignal} onChange={event => setDemandSignal(event.target.value)} className="border rounded-lg p-3 font-normal" rows={3} placeholder="Example: affordable backup power for small South African businesses" /></label><button onClick={queueDiscovery} disabled={demandSignal.trim().length < 10} className="btn btn-primary mt-3">Queue AI research</button></div><div className="mt-8 grid gap-5">{items.length === 0 ? <p className="card p-6">Nothing is ready for review yet.</p> : items.map(item => <article key={item.id} className="card p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-semibold">{item.title}</h2><p className="mt-2 text-gray-600">{item.demand_summary || 'No demand summary provided.'}</p><p className="mt-3 text-sm">Product: {item.proposed_product?.name || 'Not prepared'} · Supplier: {item.proposed_supplier?.business_name || 'Not linked'} · Confidence: {item.confidence ? `${Math.round(item.confidence * 100)}%` : 'Not scored'} · Estimated margin: {item.estimated_margin ? `${item.estimated_margin}%` : 'Not scored'}</p>{item.source_url && <a href={item.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-primary underline">Research source</a>}</div><button onClick={() => approve(item.id)} className="btn btn-primary self-start">Approve & publish</button></div></article>)}</div>{message && <p role="status" className="mt-5 text-sm">{message}</p>}</section>
}
