import Link from 'next/link'

const principles = [
  ['Trusted marketplace', 'We review suppliers before products can be listed for customers to discover.'],
  ['Supplier-led fulfilment', 'Suppliers prepare and deliver their own orders, while ConnectNetwork manages the marketplace experience.'],
  ['Clear paid placements', 'Sponsored products and businesses are visibly labelled so shoppers can make informed choices.'],
  ['Growing together', 'We help buyers discover useful products and give local suppliers a practical route to more customers.']
]

export default function AboutClient() { return <main className="container-section py-16"><section className="max-w-3xl"><p className="font-semibold text-green">ABOUT CONNECTNETWORK</p><h1 className="section-title mt-2">A marketplace built to connect shoppers and suppliers.</h1><p className="section-subtitle mt-5">ConnectNetwork brings products from approved suppliers into one online marketplace. Customers can browse, pay securely, and follow their orders, while suppliers manage the products and fulfilment they know best.</p></section><section className="mt-16 grid gap-5 md:grid-cols-2">{principles.map(([title, text]) => <article className="card p-7" key={title}><h2 className="text-xl font-bold text-primary">{title}</h2><p className="mt-3 text-slate-600">{text}</p></article>)}</section><section className="mt-16 rounded-3xl bg-slate-50 p-8 md:p-12"><h2 className="text-3xl font-bold">How marketplace orders work</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{[['1', 'Browse', 'Find products from approved suppliers.'], ['2', 'Pay', 'Complete a secure checkout with ConnectNetwork.'], ['3', 'Receive', 'Your supplier prepares and delivers your order.']].map(([number, title, text]) => <div key={number}><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary font-bold text-white">{number}</span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-600">{text}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="btn btn-primary">Shop products</Link><Link href="/suppliers" className="btn btn-ghost">Become a supplier</Link></div></section></main> }
